### ISSUE TITLE
Euro qualifying results

### ISSUE THREAD

**Issue by ChristopherDavisUCI** [martj42/womens-international-results#1]
Hi!  Thanks for providing all this data!  I don't know if it can be helpful, but I've attached here results I gathered of (I think all) the Euro qualifying matches for the upcoming tournament:

[euro-quals-and-playoffs.csv](https://github.com/martj42/womens-international-results/files/8952074/euro-quals-and-playoffs.csv)

As far as I can tell, 38 of these 206 already appear in your data.

I did a couple reality checks, but there could definitely be mistakes.  I didn't do any searching to find out if some of these were at neutral locations.  If there's anything easy I can do to make it more useful, just let me know!

**Comment by ChristopherDavisUCI** [comment]
Here's a similar file for Women's world cup qualifiers (UEFA teams only).  Same caveats as above, thanks again!

[wwc-qual-uefa.csv](https://github.com/martj42/womens-international-results/files/8952757/wwc-qual-uefa.csv)

**Comment by martj42** [comment]
Hey, thanks for reminding me this exist! I added ~600 new results. My scrapers can get the results off wikipedia easily enough with the match location info included so there's no need for your csv files right now. I didn't add the World Cup qualification results yet so if you want to, you can submit a pull request with the full info and I'll accept. Otherwise I'll wait until all the qualifying matches have been played.

Peace ☮️

**Comment by ChristopherDavisUCI** [comment]
Hi @martj42

Thanks for your help last year!  Is it easy for you to update the international results again?  Big tournament coming up ;)

No worries if you don't have time.  Thanks either way!

**Comment by martj42** [comment]
Updated now. Added the euro qualis and a bunch of the little friendly tournaments that women's football has.

**Comment by ChristopherDavisUCI** [comment]
Thanks again very much!  I look forward to reaching out again around June 2025.

**Comment by martj42** [comment]
See you then.
